site:
  title: Fleet
  url: /
  start_page: 0.14@ROOT:ROOT:index.adoc

content:
  sources:
    - url: ./
      start_paths: [community-docs/next, community-docs/v0.14, community-docs/v0.13, community-docs/v0.12,community-docs/v0.11, community-docs/v0.10,community-docs/v0.9]
      branches: HEAD

urls:
  html_extension_style: drop

# Description: SUSE UI bundle
ui:
  bundle:
  # Fix the issue to point to the raw file download link
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./community-supp-files

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
    product: fleet
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
  - require: '@springio/antora-xref-extension'

output:
  dir: build/site-community
